#!/usr/bin/env bash
##===----------------------------------------------------------------------===##
##
## This source file is part of the TDSNIO open source project
##
## Copyright (c) 2026 Aaron Edwards and the TDSNIO project authors
## Licensed under Apache License v2.0
##
## See LICENSE for license information
## See CONTRIBUTORS.md for the list of TDSNIO project authors
##
## SPDX-License-Identifier: Apache-2.0
##
##===----------------------------------------------------------------------===##

set -euo pipefail

CURRENT_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_ROOT="$(git -C "${CURRENT_SCRIPT_DIR}" rev-parse --show-toplevel)"

# 1.
CONTRIBUTORS=$( cd "$CURRENT_SCRIPT_DIR"/.. && git shortlog -es | cut -f2 | sed 's/^/- /' )

# 2.
cat > "$REPO_ROOT/CONTRIBUTORS.md" <<- EOF
# Contributors

Thanks to everyone who has contributed to this project over time.

This list reflects historical contributions and does not imply current maintenance responsibility or endorsement of the present codebase.

$CONTRIBUTORS

**Updating this list**

Please do not edit this file manually. It is generated using \`bash ./scripts/generate-contributors-list.sh\`.
If a name is misspelled or appearing multiple times: add an entry in \`./.mailmap\`.
EOF
